stages:
  make_features:
    cmd: python scripts/make_features.py --params params.yaml
    deps:
      - scripts/make_features.py
      - data/gold_link_window_features_delta
      - params.yaml
    outs:
      - data/features/features.parquet

  train_arima:
    cmd: python scripts/train_arima.py --params params.yaml
    deps:
      - scripts/train_arima.py
      - data/features/features.parquet
      - params.yaml
    outs:
      - models/arima
    metrics:
      - reports/metrics/arima.json:
          cache: false

  train_xgb:
    cmd: python scripts/train_xgb.py --params params.yaml
    deps:
      - scripts/train_xgb.py
      - data/features/features.parquet
      - params.yaml
    outs:
      - models/xgb
    metrics:
      - reports/metrics/xgb.json:
          cache: false

  train_lstm:
    cmd: python scripts/train_lstm.py --params params.yaml
    deps:
      - scripts/train_lstm.py
      - data/features/features.parquet
      - params.yaml
    outs:
      - models/lstm
    metrics:
      - reports/metrics/lstm.json:
          cache: false

  evaluate:
    cmd: python scripts/evaluate.py --params params.yaml
    deps:
      - scripts/evaluate.py
      - reports/metrics/arima.json
      - reports/metrics/xgb.json
      - reports/metrics/lstm.json
      - params.yaml
    metrics:
      - reports/metrics/summary.json:
          cache: false
