stages:
  ingest:
    cmd: python scripts/ingest.py data/raw data/clean
    deps:
      - data/raw
      - scripts/ingest.py
    outs:
      - data/clean

  featurise:
    cmd: python scripts/featurise.py data/clean data/features
    deps:
      - data/clean
      - scripts/featurise.py
    outs:
      - data/features

  train:
    cmd: python scripts/train.py data/features models/baseline.joblib
    deps:
      - data/features
      - scripts/train.py
    params:
      - model.n_estimators
      - model.max_depth
      - model.learning_rate
    outs:
      - models/baseline.joblib
    metrics:
      - metrics/metrics.json:
          cache: false
