stages:
  ingest:
    cmd: python scripts/ingest.py data/raw data/clean
    deps:
    - data/raw
    - scripts/ingest.py
    outs:
    - data/clean
  featurise:
    cmd: python scripts/featurise.py data/clean data/features
    deps:
    - data/clean
    - scripts/featurise.py
    outs:
    - data/features
  train:
    cmd: python scripts/train.py data/features models/baseline.joblib
    deps:
    - data/features
    - scripts/train.py
    params:
    - model.n_estimators
    - model.max_depth
    - model.learning_rate
    outs:
    - models/baseline.joblib
    metrics:
    - metrics/metrics.json:
        cache: false
  validate_features:
    cmd: python scripts/validate_features.py
    deps:
    - data/features/train.parquet
    - schema/aliases.yaml
    - params.yaml
    - scripts/validate_features.py
    outs:
    - reports/schema_report.json
  train_xgb:
    cmd: python scripts/train_xgb.py
    deps:
    - data/features/train.parquet
    - data/features/test.parquet
    - params.yaml
    - scripts/train_xgb.py
    outs:
    - models/xgb.joblib
    metrics:
    - metrics/xgb.json:
        cache: false
  reshape_windows:
    cmd: python scripts/make_windows.py
    deps:
    - data/features/train.parquet
    - data/features/test.parquet
    - params.yaml
    - scripts/make_windows.py
    outs:
    - data/windows/X_train.npy
    - data/windows/y_train.npy
    - data/windows/X_val.npy
    - data/windows/y_val.npy
    - data/windows/X_test.npy
    - data/windows/y_test.npy
    - data/windows/manifest.json
  train_lstm:
    cmd: python scripts/train_lstm.py
    deps:
    - data/windows/X_train.npy
    - data/windows/y_train.npy
    - data/windows/X_val.npy
    - data/windows/y_val.npy
    - data/windows/X_test.npy
    - data/windows/y_test.npy
    - params.yaml
    - scripts/train_lstm.py
    outs:
    - models/lstm.pt
    metrics:
    - metrics/lstm.json:
        cache: false
  select_champion:
    cmd: python scripts/select_champion.py
    deps:
    - metrics/metrics.json
    - metrics/xgb.json
    - metrics/lstm.json
    - scripts/select_champion.py
    outs:
    - models/champion.json
plots:
- metrics/xgb.json:
    x: curvesteps
    y: curves.validation.rmse
    title: XGB validation RMSE
    template: simple
    x_label: step
    y_label: rmse
- metrics/lstm.json:
    x: curves.epoch
    y: curves.val_rmse
    title: LSTM validation RMSE
    template: simple
    x_label: epoch
    y_label: rmse
- metrics/xgb.json:
    x: curvesteps
    y: curves.validation.rmse
    title: XGB validation RMSE
    template: simple
    x_label: step
    y_label: rmse
- metrics/lstm.json:
    x: curves.epoch
    y: curves.val_rmse
    title: LSTM validation RMSE
    template: simple
    x_label: epoch
    y_label: rmse
