model:
  n_estimators: 200
  max_depth: 3
  learning_rate: 0.05
data:
  test_size: 0.2        # proportion of last‐period rows held out
features:
  lags: [1, 2, 3, 6]    # hours to lag for autocorrelation
target: rapl_power_total_watts
