# version: "3.9"

services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      # make sure this file exists at repo root; see snippet below
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -h 127.0.0.1 -t test -C 1 -W 2 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports: ["2181:2181"]
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 12

  kafka-init:
    image: bitnami/kafka:3.7
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./docker/kafka_streaming/topics.sh:/app/topics.sh:ro
    environment:
      - BOOTSTRAP=kafka:9092
    entrypoint: ["/bin/bash","-lc","bash /app/topics.sh && echo 'topics initialised' && sleep 1"]
    restart: "no"


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on: [kafka]
    restart: unless-stopped

  # The bridge containerised
  mqtt_to_kafka:
    build: ./docker/kafka_streaming
    container_name: mqtt_to_kafka
    environment:
      MQTT_BROKER: mqtt
      MQTT_PORT: 1883
      MQTT_TOPIC: ecc/metrics/#
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: metrics.raw.stream
    depends_on: [mqtt, kafka]
    restart: unless-stopped
