provider:
  name: openfaas
  gateway: http://localhost:31110

functions:
  resize:
    image: goncaloferreirauva/resize:latest
    skip_build: true
    annotations:
      prometheus.io.scrape: "true"
      prometheus.io.port: "8082"
    podSpecPatch: |
      containers:
        - name: power-exporter
          image: quay.io/prometheus/node-exporter:v1.8.1
          args:
            - "--collector.textfile.directory=/var/power"
